
<?php
//var_dump($block);
//var_dump($_REQUEST);

    $order = \Magento\Framework\App\ObjectManager::getInstance()->create('\Magento\Sales\Model\Order')->loadByIncrementId((int)$_REQUEST['invoice']);
	
	
	if($_REQUEST['t']=="f"){
		echo "<h1 class='page-title'>Payment failed.</h1>";
		echo "order: #".$order->getIncrementId()."<br/>";
		
		if(!empty($_REQUEST['error'])){
			echo "Reasons for failure: ".$_REQUEST['error'];
		}
		
	}
	else{
		echo "<h1 class='page-title'>We received your order!</h1>";
		echo $block->msgSuccess() . $order->getIncrementId();
	}
	
    
   
?>